-- Reset services to match src/content/services.ts canonical list
DELETE FROM public.services;

INSERT INTO public.services (
  slug,
  name,
  short_description,
  description,
  price,
  price_suv,
  price_van,
  estimated_duration_minutes,
  featured,
  features,
  image_url,
  category,
  is_active,
  sort_order
) VALUES
(
    'premium-interior-deep-clean',
    'Premium Interior Deep Clean',
    'A professional deep clean tailored to your vehicle''s interior materials, age and condition.',
    'A professional deep clean tailored to your vehicle''s interior materials, age and condition.

Vehicles with excessive soiling, heavy staining, pet hair, strong odours or requiring specialist treatment may incur an additional charge.',
    159,
    159,
    159,
    480,
    true,
    ARRAY['Thorough interior vacuum', 'Deep carpet & floor cleaning', 'Upholstery cleaning where appropriate', 'Plastics & interior trim cleaning & treatment', 'Leather cleaning & conditioning where applicable', 'Steam cleaning where suitable', 'Detailed finishing', 'Includes a complimentary basic exterior wash'],
    '/premium-interior-deep-clean.jpg',
    'standard',
    true,
    0
  ),
(
    'exterior-detail',
    'Exterior Detail',
    'A thorough exterior refresh designed to safely clean, maintain and enhance your vehicle''s appearance.',
    'A thorough exterior refresh designed to safely clean, maintain and enhance your vehicle''s appearance.',
    159,
    159,
    159,
    480,
    true,
    ARRAY['Safe pre-wash & hand wash', 'Deep wheel & rim cleaning', 'Wheel arches & under-arches', 'Exterior detailing & finishing'],
    '/exterior-detail-v2.jpg',
    'standard',
    true,
    1
  ),
(
    'complete-detail',
    'Complete Detail',
    'Our complete interior and exterior refresh — the ideal choice for customers looking to thoroughly refresh the entire vehicle.',
    'Our complete interior and exterior refresh. The ideal choice for customers looking to thoroughly refresh the entire vehicle.',
    289,
    289,
    289,
    480,
    true,
    ARRAY['Includes: Premium Interior Deep Clean', 'Includes: Exterior Detail'],
    '/complete-detail.jpg',
    'bundle',
    true,
    2
  ),
(
    'paint-enhancement',
    'Paint Enhancement',
    'A more intensive exterior treatment designed to restore gloss, improve paint clarity and enhance the overall appearance of the paintwork.',
    'A more intensive exterior treatment designed to restore gloss, improve paint clarity and enhance the overall appearance of the paintwork.

Heavily scratched, oxidised or neglected paintwork requiring additional correction will be assessed and quoted separately.',
    279,
    279,
    279,
    480,
    true,
    ARRAY['Safe pre-wash & hand wash', 'Deep wheel & rim cleaning', 'Wheel arches & under-arches', 'Iron & tar decontamination', 'Clay bar treatment', 'Machine paint enhancement'],
    '/paint-enhancement.jpg',
    'standard',
    true,
    3
  ),
(
    'complete-paint-enhancement',
    'Complete Paint Enhancement',
    'The complete inside-and-out treatment — ideal for customers looking for a complete vehicle transformation.',
    'The complete inside-and-out treatment. Ideal for customers looking for a complete vehicle transformation.',
    419,
    419,
    419,
    480,
    false,
    ARRAY['Includes: Paint Enhancement', 'Includes: Premium Interior Deep Clean'],
    '/complete-paint-enhancement.jpg',
    'bundle',
    true,
    4
  ),
(
    'premium-wax-protection',
    'Premium Wax Protection',
    'Enhanced gloss, water repellency and up to 9 months of protection.',
    'Enhanced gloss, water repellency and up to 9 months of protection. Protection can be added to any suitable Paint Enhancement service.',
    129,
    129,
    129,
    480,
    false,
    ARRAY['Enhanced gloss finish', 'Water repellency', 'Up to 9 months of protection'],
    '/premium-wax-protection.jpg',
    'protection',
    true,
    5
  ),
(
    'ceramic-paint-protection',
    '1-Year Ceramic Paint Protection',
    'Enhanced gloss, strong hydrophobic properties and long-lasting paint protection.',
    'Enhanced gloss, strong hydrophobic properties and long-lasting paint protection. Protection can be added to any suitable Paint Enhancement service.',
    199,
    199,
    199,
    480,
    false,
    ARRAY['Enhanced gloss finish', 'Strong hydrophobic properties', 'Long-lasting paint protection'],
    '/ceramic-paint-protection.jpg',
    'protection',
    true,
    6
  ),
(
    'exterior-glass-ceramic',
    'Exterior Glass Ceramic Coating',
    'Enhanced water repellency and improved visibility during wet conditions.',
    'Enhanced water repellency and improved visibility during wet conditions. Protection can be added to any suitable Paint Enhancement service.',
    79,
    79,
    79,
    480,
    false,
    ARRAY['Enhanced water repellency', 'Improved visibility in wet conditions'],
    '/exterior-glass-ceramic-coating.jpg',
    'protection',
    true,
    7
  ),
(
    'engine-bay-detail',
    'Engine Bay Detail',
    'A careful and detailed engine bay clean using appropriate products and techniques around sensitive components.',
    'A careful and detailed engine bay clean using appropriate products and techniques around sensitive components.',
    89,
    89,
    89,
    480,
    false,
    ARRAY['Safe degreasing', 'Hand brush agitation', 'Plastic & rubber dressing', 'Protected electrical areas'],
    '/engine-bay-detail.jpg',
    'standard',
    true,
    8
  ),
(
    'signature-detail',
    'Signature Detail',
    'Our ultimate complete vehicle transformation — a complete inside-and-out detail finished with long-lasting ceramic protection.',
    'Our ultimate complete vehicle transformation. A complete inside-and-out detail finished with long-lasting ceramic protection.',
    599,
    599,
    599,
    480,
    false,
    ARRAY['Includes: Paint Enhancement', 'Includes: Premium Interior Deep Clean', 'Includes: 1-Year Ceramic Paint Protection'],
    '/signature-detail.jpg',
    'bundle',
    true,
    9
  ),
(
    'signature-detail-glass-protection',
    'Signature Detail + Glass Protection',
    'Everything included in the Signature Detail, plus exterior glass ceramic coating — the ultimate inside-and-out detailing and protection package.',
    'Everything included in the Signature Detail, plus exterior glass ceramic coating. The ultimate inside-and-out detailing and protection package.',
    669,
    669,
    669,
    480,
    false,
    ARRAY['Includes: Paint Enhancement', 'Includes: Premium Interior Deep Clean', 'Includes: 1-Year Ceramic Paint Protection', 'Includes: Exterior Glass Ceramic Coating'],
    '/signature-detail-glass-protection.jpg',
    'bundle',
    true,
    10
  );